#!/bin/bash

echo "CLEANING"
rm -f cmake_install.cmake
rm -f compile_commands.json
rm -f CMakeCache.txt
rm -f libcore.a
rm -f libkissat.a
rm -f Makefile
rm -f -r CMakeFiles
rm -f main
rm -f gen
rm -f stats
rm -f -r build
rm -f -r .cache